services:
  # --- Base de Données ---
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hackathon-network

  # --- Interface Base de Données ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_client
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - hackathon-network

  # --- Backend (Spring Boot) ---
  backend:
    container_name: hackathon_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hackathon_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - hackathon-network

  # --- Frontend (Mode Dev) ---
  frontend:
    container_name: hackathon_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    # Mapping direct du port Vite (5173)
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - hackathon-network

volumes:
  mysql_data:

networks:
  hackathon-network:
    driver: bridge