services:
  # --- Service Base de Données ---
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    # Redémarrer automatiquement si ça plante
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # Le nom de la BDD doit correspondre à application.properties
      MYSQL_DATABASE: hackathon_db
    ports:
      - "3306:3306"
    volumes:
      # Pour garder les données même si on éteint le container
      - mysql_data:/var/lib/mysql

  # --- Service PhpMyAdmin (bonus visuel) ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_client
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"

# Déclaration du volume pour le stockage persistant
volumes:
  mysql_data: